### ISSUE TITLE
Update CHECKLIST.rst

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Previewer#15]
Once the work has been done in Iteration 1, the CHECKLIST.rst will need to be updated

**Comment by caprenter** [comment]
We are waiting for Registry updates to take place. Once those are in place this task should be simple enough.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), the Preview Tool is to be closed down and no new features will be added before that point.
