### ISSUE TITLE
Better UI handling of 2.01 data?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Previewer#19]
On previewing 2.01 data it "appears" that - for example - an activity doesnt have a title / description:

http://preview.iatistandard.org/index.php?url=http%3A//www.publishwhatyoufund.org/iatidata/pwyf-998.xml

As the text for title/description is held within the `narrative` element, it can be accessed through the + sign.  

It might be worth investigating how to better handle this

**Comment by stevieflow** [comment]
As more publishers utilise 2.01, it would be useful to know if this can be addressed

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), the Preview Tool is to be closed down and no new features will be added before that point.
